    # root = LinkedList()
    # root.insert_at_begining(10)
    # root.insert_at_begining(5)
    # root.insert_at_end(15)
    # root.insert_at(2, 567)
    # root.print()
    # root.remove_at(3)
    # root.print()